<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="3" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-05-27T18:29:28 IST" name="Regression API Test Suite" finished-at="2020-05-27T18:29:47 IST" duration-ms="18735">
    <groups>
    </groups>
    <test started-at="2020-05-27T18:29:28 IST" name="Driscolls API App Test Cases" finished-at="2020-05-27T18:29:47 IST" duration-ms="18735">
      <class name="com.enquero.api.driscolls.tests.EmployeeTest">
        <test-method is-config="true" signature="beforeTest()[pri:0, instance:com.enquero.api.driscolls.tests.EmployeeTest@1698d7c0]" started-at="2020-05-27T18:29:28 IST" name="beforeTest" finished-at="2020-05-27T18:29:31 IST" duration-ms="3225" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method signature="getEmployeeDetails()[pri:0, instance:com.enquero.api.driscolls.tests.EmployeeTest@1698d7c0]" started-at="2020-05-27T18:29:37 IST" name="getEmployeeDetails" finished-at="2020-05-27T18:29:37 IST" duration-ms="946" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [success] but found [fail]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [success] but found [fail]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.enquero.api.driscolls.tests.EmployeeTest.getEmployeeDetails(EmployeeTest.java:75)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:204)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getEmployeeDetails -->
        <test-method signature="postEmployeeDetails()[pri:1, instance:com.enquero.api.driscolls.tests.EmployeeTest@1698d7c0]" started-at="2020-05-27T18:29:40 IST" name="postEmployeeDetails" finished-at="2020-05-27T18:29:41 IST" duration-ms="1006" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postEmployeeDetails -->
        <test-method signature="getEmployeeIdDetails()[pri:2, instance:com.enquero.api.driscolls.tests.EmployeeTest@1698d7c0]" started-at="2020-05-27T18:29:42 IST" name="getEmployeeIdDetails" finished-at="2020-05-27T18:29:43 IST" duration-ms="970" status="FAIL">
          <exception class="java.lang.NoSuchMethodError">
            <message>
              <![CDATA['void org.hamcrest.Matcher.describeMismatch(java.lang.Object, org.hamcrest.Description)']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NoSuchMethodError: 'void org.hamcrest.Matcher.describeMismatch(java.lang.Object, org.hamcrest.Description)'
at io.restassured.internal.util.MatcherErrorMessageBuilder.buildError(MatcherErrorMessageBuilder.java:19)
at io.restassured.internal.util.MatcherErrorMessageBuilder$buildError.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validateStatusCodeAndStatusLine(ResponseSpecificationImpl.groovy:536)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:449)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:643)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:122)
at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:130)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:117)
at com.enquero.apiutility.RestUtil.getRequest(RestUtil.java:208)
at com.enquero.api.driscolls.tests.EmployeeTest.getEmployeeIdDetails(EmployeeTest.java:130)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:204)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NoSuchMethodError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getEmployeeIdDetails -->
        <test-method signature="updateEmployeeDetails()[pri:3, instance:com.enquero.api.driscolls.tests.EmployeeTest@1698d7c0]" started-at="2020-05-27T18:29:45 IST" name="updateEmployeeDetails" finished-at="2020-05-27T18:29:46 IST" depends-on-methods="com.enquero.api.driscolls.tests.EmployeeTest.postEmployeeDetails" duration-ms="903" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- updateEmployeeDetails -->
        <test-method signature="deleteEmployeeRecord()[pri:4, instance:com.enquero.api.driscolls.tests.EmployeeTest@1698d7c0]" started-at="2020-05-27T18:29:46 IST" name="deleteEmployeeRecord" finished-at="2020-05-27T18:29:47 IST" depends-on-methods="com.enquero.api.driscolls.tests.EmployeeTest.updateEmployeeDetails" duration-ms="990" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteEmployeeRecord -->
        <test-method is-config="true" signature="afterTest()[pri:0, instance:com.enquero.api.driscolls.tests.EmployeeTest@1698d7c0]" started-at="2020-05-27T18:29:47 IST" name="afterTest" finished-at="2020-05-27T18:29:47 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- com.enquero.api.driscolls.tests.EmployeeTest -->
    </test> <!-- Driscolls API App Test Cases -->
  </suite> <!-- Regression API Test Suite -->
</testng-results>
